sun_angle = 48.0
track = "acu_bathurst"
time_of_day_multiplier = 1.0

[server]
name = "Test Assetto Server"
address = "0.0.0.0"
tcp_port = 9600
udp_port = 9600
http_port = 8080
max_clients = 10
client_send_interval_hz = 20
welcome_message = "Assetto Corsa Server in Rust by Nokkasiili"

[game]
legal_tyres = "idk"
force_virtual_mirror = false
tc_allowed =  0
abs_allowed =  0
stability_allowed = false
autoclutch_allowed = false
tyre_blankets_allowed = true
allowed_tyres = 2
tyre_wear_rate = 1.0
fuel_rate = 1.0
start_rule = 0
damage_multiplier = 1.0
max_contacts_per_km = 5
vote_duration = 10000
has_extra_lap = false
pit_window_start = 0
pit_window_end = 0
race_gas_penalty_disabled=false


[dynamictrack]
enabled = true
base_grip = 1.0
session_start_grip = 1.0
grip_per_lap = 0.1
random_grip = 0.1
session_transfer = 0.1

[[weathers]]
  graphics = "3_clear"
  base_ambient=21
  base_road=30
  variation_ambient=1
  variation_road=12
  [weathers.wind]
  base_speed_min=1
  base_speed_max=4
  base_direction=3
  variation_direction=20

[log]
level = "debug"

[[cars]]
model="ks_mercedes_190_evo2"
skin="Blue71"

[[cars]]
model="ks_mercedes_190_evo2"
skin="Blue71"

[[cars]]
model="ks_mercedes_190_evo2"
skin="Blue71"



[sessions]
result_screen_time = 10000
race_over_time = 30000
  [[sessions.sessions]]
  name="Qualify"
  session_type=1
  time=20000
  laps=30
